services:
  nginx:
    build: 
      context: ./requirement/nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - ./web:/var/www/html

  wordpress:
    build: 
      context: ./requirement/wordpress
    container_name: wp_php
    volumes:
      - ./web:/var/www/html

  mariadb:
    build: ./requirement/mariadb
    container_name: mariadb

volumes:
  web:
  wordpress_data: