services:
  nginx:
    build: 
      context: ./requirement/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - ./web:/var/www/html
    networks:
      inception:

  wordpress:
    build: 
      context: ./requirement/wordpress
    container_name: wp_php
    volumes:
      - ./web:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      inception:

  mariadb:
    build: ./requirement/mariadb
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      inception:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  web:
  wordpress_data:

networks:
  inception: