version: "3.8"

services:
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html
    expose:
      - 9000

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress

volumes:
  wp_data:
