services:
  nginx:
    build: requirements/nginx
    ports:
      - "80:80"
    networks:
      - webnet
    volumes:
      - ./web:/var/www/html
  wordpress:
    build: requirements/wordpress
    networks:
      - webnet
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    build: requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - webnet
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  webnet:

volumes:
  mariadb_data: